version: '3.9'

services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_NAME}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - monpoly_network

volumes:
  mongodb_data:
    driver: local

networks:
  monpoly_network:
    name: monpoly_network
    driver: bridge